# Generated by Django 3.2.11 on 2022-01-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algo_type', models.CharField(max_length=200)),
                ('algo_thumbnail', models.ImageField(upload_to='algo_thumbs/')),
            ],
        ),
    ]
