# Generated by Django 3.2.11 on 2022-02-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0004_dataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='id',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
