# Generated by Django 3.2.11 on 2022-02-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0006_delete_dataset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
